
package relatorios;

import conexoes.ConexaoFirebird;
import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

public class DAORelatorios1
extends ConexaoFirebird {
    private final String NOME_DO_RELATORIO = "C:/Sistema Assistencia OS/temp/" + new Date().getTime() + ".pdf";

    public boolean relatorioClienteDAO() {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.BLOQUEADO AS TBL_CLIENTE_BLOQUEADO,     TBL_CLIENTE.FISICO_JURIDICO AS TBL_CLIENTE_FISICO_JURIDICO,     TBL_CLIENTE.FK_REPRESENTANTE AS TBL_CLIENTE_FK_REPRESENTANTE,     TBL_CLIENTE.FK_FORMA_PAGAMENTO AS TBL_CLIENTE_FK_FORMA_PAGAMENTO,     TBL_CLIENTE.FK_TABELA_PRECO AS TBL_CLIENTE_FK_TABELA_PRECO,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_CLIENTE.DATA_NASCIMENTO AS TBL_CLIENTE_DATA_NASCIMENTO,     TBL_CLIENTE.DATA_CADASTRO AS TBL_CLIENTE_DATA_CADASTRO,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM FROM      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA,      TBL_CLIENTE TBL_CLIENTE;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioCliente.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioOrcamentoPedidoCompletoTemperado(int pCodOrcamento) {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORMA_PAGAMENTO.PK_CODIGO AS TBL_FORMA_PAGAMENTO_PK_CODIGO,     TBL_FORMA_PAGAMENTO.NOME AS TBL_FORMA_PAGAMENTO_NOME,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_ORCAMENTO.PK_CODIGO AS TBL_ORCAMENTO_PK_CODIGO,     TBL_ORCAMENTO.DATA_ORCAMENTO AS TBL_ORCAMENTO_DATA_ORCAMENTO,     TBL_ORCAMENTO.DATA_VALIDADE AS TBL_ORCAMENTO_DATA_VALIDADE,     TBL_ORCAMENTO.DATA_ENTREGA AS TBL_ORCAMENTO_DATA_ENTREGA,     TBL_ORCAMENTO.REFERENCIA_CLIENTE AS TBL_ORCAMENTO_REFERENCIA_CLIENT,     TBL_ORCAMENTO.STATUS AS TBL_ORCAMENTO_STATUS,     TBL_ORCAMENTO.OBSERVACAO AS TBL_ORCAMENTO_OBSERVACAO,     TBL_ORCAMENTO.ORDEM_PRODUCAO AS TBL_ORCAMENTO_ORDEM_PRODUCAO,     TBL_ORCAMENTO.CONTA_PROCESSADA AS TBL_ORCAMENTO_CONTA_PROCESSADA,     TBL_ORCAMENTO.TOTAL_M2_VIDRO AS TBL_ORCAMENTO_TOTAL_M2_VIDRO,     TBL_PROJETO.PK_CODIGO AS TBL_PROJETO_PK_CODIGO,     TBL_PROJETO.NOME AS TBL_PROJETO_NOME,     TBL_LISTA_DE_PROD_DO_ORCA.QUANTIDADE AS TBL_LISTA_DE_PROD_DO_ORCA_QUANT,     TBL_LISTA_DE_PROD_DO_ORCA.ALTURA AS TBL_LISTA_DE_PROD_DO_ORCA_ALTUR,     TBL_LISTA_DE_PROD_DO_ORCA.LARGURA AS TBL_LISTA_DE_PROD_DO_ORCA_LARGU,     TBL_LISTA_DE_PROD_DO_ORCA.PERCENTUAL_DESCONTO AS TBL_LISTA_DE_PROD_DESCO,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_BRUTO AS TBL_LISTA_DE_PROD_VALOR_BRU,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_UNITARIO AS TBL_LISTA_DE_PROD_VALOR_UNIT,     TBL_VALOR_TOTAL_ORCA.PK_CODIGO AS TBL_VALOR_TOTAL_ORCA_PK_CODIGO,     TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO AS TBL_VALOR_TOTAL_ORCA_FK_CODIGO_,     TBL_VALOR_TOTAL_ORCA.VALOR_BRUTO AS TBL_VALOR_TOTAL_ORCA_VALOR_BRUT,     TBL_VALOR_TOTAL_ORCA.VALOR_DESCONTO AS TBL_VALOR_TOTAL_ORCA_VALOR_DESC,     TBL_VALOR_TOTAL_ORCA.VALOR_FINAL_VENDA AS TBL_VALOR_TOTAL_ORCA_VALOR_FINA,     TBL_VALOR_TOTAL_ORCA.DESCONTO_EM_REAIS AS TBL_VALOR_TOTAL_ORCA_DESCONTO_E,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_ORCAMENTO.TEMPERADO_COMUM AS TBL_ORCAMENTO_TEMPERADO_COMUM,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_IMAGEM_PROJETO.IMAGEM AS TBL_IMAGEM_PROJETO_IMAGEM  FROM      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_ORCAMENTO TBL_ORCAMENTO ON TBL_CLIENTE.PK_CODIGO = TBL_ORCAMENTO.FK_CLIENTE      INNER JOIN TBL_PROJETO TBL_PROJETO ON TBL_ORCAMENTO.FK_PROJETO = TBL_PROJETO.PK_CODIGO      INNER JOIN TBL_LISTA_DE_PROD_DO_ORCA TBL_LISTA_DE_PROD_DO_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_ORCAMENTO      INNER JOIN TBL_VALOR_TOTAL_ORCA TBL_VALOR_TOTAL_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO      INNER JOIN TBL_FORMA_PAGAMENTO TBL_FORMA_PAGAMENTO ON TBL_ORCAMENTO.FK_FORMA_PAGAMENTO = TBL_FORMA_PAGAMENTO.PK_CODIGO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ORCAMENTO.FK_COR = TBL_COR_FERRAG_PROJETO.COD_COR      INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_PRODUTO = TBL_PRODUTO.PK_CODIGO      INNER JOIN TBL_IMAGEM_PROJETO TBL_IMAGEM_PROJETO ON TBL_PROJETO.PK_CODIGO = TBL_IMAGEM_PROJETO.FK_CODIGO_PROJETO,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA WHERE TBL_ORCAMENTO.PK_CODIGO = '" + pCodOrcamento + "'");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioOrcamento.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioOrcamentoPedidoCompletoComum(int pCodOrcamento) {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORMA_PAGAMENTO.PK_CODIGO AS TBL_FORMA_PAGAMENTO_PK_CODIGO,     TBL_FORMA_PAGAMENTO.NOME AS TBL_FORMA_PAGAMENTO_NOME,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_ORCAMENTO.PK_CODIGO AS TBL_ORCAMENTO_PK_CODIGO,     TBL_ORCAMENTO.DATA_ORCAMENTO AS TBL_ORCAMENTO_DATA_ORCAMENTO,     TBL_ORCAMENTO.DATA_VALIDADE AS TBL_ORCAMENTO_DATA_VALIDADE,     TBL_ORCAMENTO.DATA_ENTREGA AS TBL_ORCAMENTO_DATA_ENTREGA,     TBL_ORCAMENTO.REFERENCIA_CLIENTE AS TBL_ORCAMENTO_REFERENCIA_CLIENT,     TBL_ORCAMENTO.STATUS AS TBL_ORCAMENTO_STATUS,     TBL_ORCAMENTO.OBSERVACAO AS TBL_ORCAMENTO_OBSERVACAO,     TBL_ORCAMENTO.ORDEM_PRODUCAO AS TBL_ORCAMENTO_ORDEM_PRODUCAO,     TBL_ORCAMENTO.CONTA_PROCESSADA AS TBL_ORCAMENTO_CONTA_PROCESSADA,     TBL_ORCAMENTO.TOTAL_M2_VIDRO AS TBL_ORCAMENTO_TOTAL_M2_VIDRO,     TBL_PROJETO.PK_CODIGO AS TBL_PROJETO_PK_CODIGO,     TBL_PROJETO.NOME AS TBL_PROJETO_NOME,     TBL_LISTA_DE_PROD_DO_ORCA.QUANTIDADE AS TBL_LISTA_DE_PROD_DO_ORCA_QUANT,     TBL_LISTA_DE_PROD_DO_ORCA.ALTURA AS TBL_LISTA_DE_PROD_DO_ORCA_ALTUR,     TBL_LISTA_DE_PROD_DO_ORCA.LARGURA AS TBL_LISTA_DE_PROD_DO_ORCA_LARGU,     TBL_LISTA_DE_PROD_DO_ORCA.PERCENTUAL_DESCONTO AS TBL_LISTA_DE_PROD_DESCO,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_BRUTO AS TBL_LISTA_DE_PROD_VALOR_BRU,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_UNITARIO AS TBL_LISTA_DE_PROD_VALOR_UNIT,     TBL_VALOR_TOTAL_ORCA.PK_CODIGO AS TBL_VALOR_TOTAL_ORCA_PK_CODIGO,     TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO AS TBL_VALOR_TOTAL_ORCA_FK_CODIGO_,     TBL_VALOR_TOTAL_ORCA.VALOR_BRUTO AS TBL_VALOR_TOTAL_ORCA_VALOR_BRUT,     TBL_VALOR_TOTAL_ORCA.VALOR_DESCONTO AS TBL_VALOR_TOTAL_ORCA_VALOR_DESC,     TBL_VALOR_TOTAL_ORCA.VALOR_FINAL_VENDA AS TBL_VALOR_TOTAL_ORCA_VALOR_FINA,     TBL_VALOR_TOTAL_ORCA.DESCONTO_EM_REAIS AS TBL_VALOR_TOTAL_ORCA_DESCONTO_E,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_ORCAMENTO.TEMPERADO_COMUM AS TBL_ORCAMENTO_TEMPERADO_COMUM,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_IMAGEM_PROJETO.IMAGEM AS TBL_IMAGEM_PROJETO_IMAGEM  FROM      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_ORCAMENTO TBL_ORCAMENTO ON TBL_CLIENTE.PK_CODIGO = TBL_ORCAMENTO.FK_CLIENTE      INNER JOIN TBL_PROJETO TBL_PROJETO ON TBL_ORCAMENTO.FK_PROJETO = TBL_PROJETO.PK_CODIGO      INNER JOIN TBL_LISTA_DE_PROD_DO_ORCA TBL_LISTA_DE_PROD_DO_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_ORCAMENTO      INNER JOIN TBL_VALOR_TOTAL_ORCA TBL_VALOR_TOTAL_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO      INNER JOIN TBL_FORMA_PAGAMENTO TBL_FORMA_PAGAMENTO ON TBL_ORCAMENTO.FK_FORMA_PAGAMENTO = TBL_FORMA_PAGAMENTO.PK_CODIGO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ORCAMENTO.FK_COR = TBL_COR_FERRAG_PROJETO.COD_COR      INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_PRODUTO = TBL_PRODUTO.PK_CODIGO      INNER JOIN TBL_IMAGEM_PROJETO TBL_IMAGEM_PROJETO ON TBL_PROJETO.PK_CODIGO = TBL_IMAGEM_PROJETO.FK_CODIGO_PROJETO,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA WHERE TBL_ORCAMENTO.PK_CODIGO = '" + pCodOrcamento + "'");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioOrcamentoComum.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean gerarRelatorioSimplificadoOrcamentoTemperado(String pCodOrcamento) {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORMA_PAGAMENTO.PK_CODIGO AS TBL_FORMA_PAGAMENTO_PK_CODIGO,     TBL_FORMA_PAGAMENTO.NOME AS TBL_FORMA_PAGAMENTO_NOME,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_ORCAMENTO.PK_CODIGO AS TBL_ORCAMENTO_PK_CODIGO,     TBL_ORCAMENTO.DATA_ORCAMENTO AS TBL_ORCAMENTO_DATA_ORCAMENTO,     TBL_ORCAMENTO.DATA_VALIDADE AS TBL_ORCAMENTO_DATA_VALIDADE,     TBL_ORCAMENTO.DATA_ENTREGA AS TBL_ORCAMENTO_DATA_ENTREGA,     TBL_ORCAMENTO.REFERENCIA_CLIENTE AS TBL_ORCAMENTO_REFERENCIA_CLIENT,     TBL_ORCAMENTO.STATUS AS TBL_ORCAMENTO_STATUS,     TBL_ORCAMENTO.OBSERVACAO AS TBL_ORCAMENTO_OBSERVACAO,     TBL_ORCAMENTO.ORDEM_PRODUCAO AS TBL_ORCAMENTO_ORDEM_PRODUCAO,     TBL_ORCAMENTO.CONTA_PROCESSADA AS TBL_ORCAMENTO_CONTA_PROCESSADA,     TBL_ORCAMENTO.TOTAL_M2_VIDRO AS TBL_ORCAMENTO_TOTAL_M2_VIDRO,     TBL_PROJETO.PK_CODIGO AS TBL_PROJETO_PK_CODIGO,     TBL_PROJETO.NOME AS TBL_PROJETO_NOME,     TBL_LISTA_DE_PROD_DO_ORCA.QUANTIDADE AS TBL_LISTA_DE_PROD_DO_ORCA_QUANT,     TBL_LISTA_DE_PROD_DO_ORCA.ALTURA AS TBL_LISTA_DE_PROD_DO_ORCA_ALTUR,     TBL_LISTA_DE_PROD_DO_ORCA.LARGURA AS TBL_LISTA_DE_PROD_DO_ORCA_LARGU,     TBL_LISTA_DE_PROD_DO_ORCA.PERCENTUAL_DESCONTO AS TBL_LISTA_DE_PROD_DO_ORCA_PERCE,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_BRUTO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_UNITARIO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_VALOR_TOTAL_ORCA.PK_CODIGO AS TBL_VALOR_TOTAL_ORCA_PK_CODIGO,     TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO AS TBL_VALOR_TOTAL_ORCA_FK_CODIGO_,     TBL_VALOR_TOTAL_ORCA.VALOR_BRUTO AS TBL_VALOR_TOTAL_ORCA_VALOR_BRUT,     TBL_VALOR_TOTAL_ORCA.VALOR_DESCONTO AS TBL_VALOR_TOTAL_ORCA_VALOR_DESC,     TBL_VALOR_TOTAL_ORCA.VALOR_FINAL_VENDA AS TBL_VALOR_TOTAL_ORCA_VALOR_FINA,     TBL_VALOR_TOTAL_ORCA.DESCONTO_EM_REAIS AS TBL_VALOR_TOTAL_ORCA_DESCONTO_E,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_ORCAMENTO.TEMPERADO_COMUM AS TBL_ORCAMENTO_TEMPERADO_COMUM,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_IMAGEM_PROJETO.IMAGEM AS TBL_IMAGEM_PROJETO_IMAGEM  FROM      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_ORCAMENTO TBL_ORCAMENTO ON TBL_CLIENTE.PK_CODIGO = TBL_ORCAMENTO.FK_CLIENTE      INNER JOIN TBL_PROJETO TBL_PROJETO ON TBL_ORCAMENTO.FK_PROJETO = TBL_PROJETO.PK_CODIGO      INNER JOIN TBL_LISTA_DE_PROD_DO_ORCA TBL_LISTA_DE_PROD_DO_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_ORCAMENTO      INNER JOIN TBL_VALOR_TOTAL_ORCA TBL_VALOR_TOTAL_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO      INNER JOIN TBL_FORMA_PAGAMENTO TBL_FORMA_PAGAMENTO ON TBL_ORCAMENTO.FK_FORMA_PAGAMENTO = TBL_FORMA_PAGAMENTO.PK_CODIGO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ORCAMENTO.FK_COR = TBL_COR_FERRAG_PROJETO.COD_COR      INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_PRODUTO = TBL_PRODUTO.PK_CODIGO      INNER JOIN TBL_IMAGEM_PROJETO TBL_IMAGEM_PROJETO ON TBL_PROJETO.PK_CODIGO = TBL_IMAGEM_PROJETO.FK_CODIGO_PROJETO,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA  WHERE TBL_PRODUTO.FK_COD_TIPO_PRODUTO = 2 AND TBL_ORCAMENTO.PK_CODIGO IN (" + pCodOrcamento + ");");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioOrcamentoRelatorio.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean gerarRelatorioSimplificadoOrcamentoComum(String pCodOrcamento) {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORMA_PAGAMENTO.PK_CODIGO AS TBL_FORMA_PAGAMENTO_PK_CODIGO,     TBL_FORMA_PAGAMENTO.NOME AS TBL_FORMA_PAGAMENTO_NOME,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_ORCAMENTO.PK_CODIGO AS TBL_ORCAMENTO_PK_CODIGO,     TBL_ORCAMENTO.DATA_ORCAMENTO AS TBL_ORCAMENTO_DATA_ORCAMENTO,     TBL_ORCAMENTO.DATA_VALIDADE AS TBL_ORCAMENTO_DATA_VALIDADE,     TBL_ORCAMENTO.DATA_ENTREGA AS TBL_ORCAMENTO_DATA_ENTREGA,     TBL_ORCAMENTO.REFERENCIA_CLIENTE AS TBL_ORCAMENTO_REFERENCIA_CLIENT,     TBL_ORCAMENTO.STATUS AS TBL_ORCAMENTO_STATUS,     TBL_ORCAMENTO.OBSERVACAO AS TBL_ORCAMENTO_OBSERVACAO,     TBL_ORCAMENTO.ORDEM_PRODUCAO AS TBL_ORCAMENTO_ORDEM_PRODUCAO,     TBL_ORCAMENTO.CONTA_PROCESSADA AS TBL_ORCAMENTO_CONTA_PROCESSADA,     TBL_ORCAMENTO.TOTAL_M2_VIDRO AS TBL_ORCAMENTO_TOTAL_M2_VIDRO,     TBL_PROJETO.PK_CODIGO AS TBL_PROJETO_PK_CODIGO,     TBL_PROJETO.NOME AS TBL_PROJETO_NOME,     TBL_LISTA_DE_PROD_DO_ORCA.QUANTIDADE AS TBL_LISTA_DE_PROD_DO_ORCA_QUANT,     TBL_LISTA_DE_PROD_DO_ORCA.ALTURA AS TBL_LISTA_DE_PROD_DO_ORCA_ALTUR,     TBL_LISTA_DE_PROD_DO_ORCA.LARGURA AS TBL_LISTA_DE_PROD_DO_ORCA_LARGU,     TBL_LISTA_DE_PROD_DO_ORCA.PERCENTUAL_DESCONTO AS TBL_LISTA_DE_PROD_DO_ORCA_PERCE,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_BRUTO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_UNITARIO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_VALOR_TOTAL_ORCA.PK_CODIGO AS TBL_VALOR_TOTAL_ORCA_PK_CODIGO,     TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO AS TBL_VALOR_TOTAL_ORCA_FK_CODIGO_,     TBL_VALOR_TOTAL_ORCA.VALOR_BRUTO AS TBL_VALOR_TOTAL_ORCA_VALOR_BRUT,     TBL_VALOR_TOTAL_ORCA.VALOR_DESCONTO AS TBL_VALOR_TOTAL_ORCA_VALOR_DESC,     TBL_VALOR_TOTAL_ORCA.VALOR_FINAL_VENDA AS TBL_VALOR_TOTAL_ORCA_VALOR_FINA,     TBL_VALOR_TOTAL_ORCA.DESCONTO_EM_REAIS AS TBL_VALOR_TOTAL_ORCA_DESCONTO_E,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_ORCAMENTO.TEMPERADO_COMUM AS TBL_ORCAMENTO_TEMPERADO_COMUM,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_IMAGEM_PROJETO.IMAGEM AS TBL_IMAGEM_PROJETO_IMAGEM  FROM      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_ORCAMENTO TBL_ORCAMENTO ON TBL_CLIENTE.PK_CODIGO = TBL_ORCAMENTO.FK_CLIENTE      INNER JOIN TBL_PROJETO TBL_PROJETO ON TBL_ORCAMENTO.FK_PROJETO = TBL_PROJETO.PK_CODIGO      INNER JOIN TBL_LISTA_DE_PROD_DO_ORCA TBL_LISTA_DE_PROD_DO_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_ORCAMENTO      INNER JOIN TBL_VALOR_TOTAL_ORCA TBL_VALOR_TOTAL_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO      INNER JOIN TBL_FORMA_PAGAMENTO TBL_FORMA_PAGAMENTO ON TBL_ORCAMENTO.FK_FORMA_PAGAMENTO = TBL_FORMA_PAGAMENTO.PK_CODIGO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ORCAMENTO.FK_COR = TBL_COR_FERRAG_PROJETO.COD_COR      INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_PRODUTO = TBL_PRODUTO.PK_CODIGO      INNER JOIN TBL_IMAGEM_PROJETO TBL_IMAGEM_PROJETO ON TBL_PROJETO.PK_CODIGO = TBL_IMAGEM_PROJETO.FK_CODIGO_PROJETO,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA  WHERE TBL_PRODUTO.FK_COD_TIPO_PRODUTO = 2 AND TBL_ORCAMENTO.PK_CODIGO IN (" + pCodOrcamento + ");");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioOrcamentoComumRelatorio.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioOrdemProducao(int pCodOrcamento) {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORMA_PAGAMENTO.PK_CODIGO AS TBL_FORMA_PAGAMENTO_PK_CODIGO,      TBL_FORMA_PAGAMENTO.NOME AS TBL_FORMA_PAGAMENTO_NOME,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_ORCAMENTO.PK_CODIGO AS TBL_ORCAMENTO_PK_CODIGO,     TBL_ORCAMENTO.DATA_ORCAMENTO AS TBL_ORCAMENTO_DATA_ORCAMENTO,     TBL_ORCAMENTO.DATA_VALIDADE AS TBL_ORCAMENTO_DATA_VALIDADE,     TBL_ORCAMENTO.DATA_ENTREGA AS TBL_ORCAMENTO_DATA_ENTREGA,     TBL_ORCAMENTO.REFERENCIA_CLIENTE AS TBL_ORCAMENTO_REFERENCIA_CLIENT,     TBL_ORCAMENTO.STATUS AS TBL_ORCAMENTO_STATUS,     TBL_ORCAMENTO.OBSERVACAO AS TBL_ORCAMENTO_OBSERVACAO,     TBL_ORCAMENTO.ORDEM_PRODUCAO AS TBL_ORCAMENTO_ORDEM_PRODUCAO,     TBL_ORCAMENTO.CONTA_PROCESSADA AS TBL_ORCAMENTO_CONTA_PROCESSADA,     TBL_ORCAMENTO.TOTAL_M2_VIDRO AS TBL_ORCAMENTO_TOTAL_M2_VIDRO,     TBL_PROJETO.PK_CODIGO AS TBL_PROJETO_PK_CODIGO,     TBL_PROJETO.NOME AS TBL_PROJETO_NOME,     TBL_LISTA_DE_PROD_DO_ORCA.QUANTIDADE AS TBL_LISTA_DE_PROD_DO_ORCA_QUANT,     TBL_LISTA_DE_PROD_DO_ORCA.ALTURA AS TBL_LISTA_DE_PROD_DO_ORCA_ALTUR,     TBL_LISTA_DE_PROD_DO_ORCA.LARGURA AS TBL_LISTA_DE_PROD_DO_ORCA_LARGU,     TBL_LISTA_DE_PROD_DO_ORCA.PERCENTUAL_DESCONTO AS TBL_LISTA_DE_PROD_DO_ORCA_PERCE,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_BRUTO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_LISTA_DE_PROD_DO_ORCA.VALOR_UNITARIO AS TBL_LISTA_DE_PROD_DO_ORCA_VALOR,     TBL_VALOR_TOTAL_ORCA.PK_CODIGO AS TBL_VALOR_TOTAL_ORCA_PK_CODIGO,     TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO AS TBL_VALOR_TOTAL_ORCA_FK_CODIGO_,     TBL_VALOR_TOTAL_ORCA.VALOR_BRUTO AS TBL_VALOR_TOTAL_ORCA_VALOR_BRUT,     TBL_VALOR_TOTAL_ORCA.VALOR_DESCONTO AS TBL_VALOR_TOTAL_ORCA_VALOR_DESC,     TBL_VALOR_TOTAL_ORCA.VALOR_FINAL_VENDA AS TBL_VALOR_TOTAL_ORCA_VALOR_FINA,     TBL_VALOR_TOTAL_ORCA.DESCONTO_EM_REAIS AS TBL_VALOR_TOTAL_ORCA_DESCONTO_E,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_ORCAMENTO.TEMPERADO_COMUM AS TBL_ORCAMENTO_TEMPERADO_COMUM,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_IMAGEM_PROJETO.IMAGEM AS TBL_IMAGEM_PROJETO_IMAGEM,     TBL_ORDEM_PRODUCAO.PK_CODIGO AS TBL_ORDEM_PRODUCAO_PK_CODIGO,     TBL_ORDEM_PRODUCAO.FK_COD_ORCAMENTO AS TBL_ORDEM_PRODUCAO_FK_COD_ORCAM,     TBL_ORDEM_PRODUCAO.FK_COD_ESTAGIO_PRODUCAO AS TBL_ORDEM_PRODUCAO_FK_COD_ESTAG,     TBL_ORDEM_PRODUCAO.DATA_GERACAO AS TBL_ORDEM_PRODUCAO_DATA_GERACAO,     TBL_ORDEM_PRODUCAO.DATA_ENTREGA_EXPEDICAO AS TBL_ORDEM_PRODUCAO_DATA_ENTREGA,     TBL_ORDEM_PRODUCAO.OBSERVACAO AS TBL_ORDEM_PRODUCAO_OBSERVACAO,     TBL_ORDEM_PRODUCAO.DATA_APROVACAO AS TBL_ORDEM_PRODUCAO_DATA_APROVAC,     TBL_ORDEM_PRODUCAO.UTILIZAR_FORMULA AS TBL_ORDEM_PRODUCAO_UTILIZAR_FOR,     TBL_ORDEM_PRODUCAO.TIPO_VIDRO AS TBL_ORDEM_PRODUCAO_TIPO_VIDRO,     TBL_ORDEM_PRODUCAO.STATUS AS TBL_ORDEM_PRODUCAO_STATUS,     TBL_ORDEM_PROD_MEDIDA.PK_CODIGO AS TBL_ORDEM_PROD_MEDIDA_PK_CODIGO,     TBL_ORDEM_PROD_MEDIDA.FK_ORDEM_PRODUCAO AS TBL_ORDEM_PROD_MEDIDA_FK_ORDEM_,     TBL_ORDEM_PROD_MEDIDA.FK_COD_PECA AS TBL_ORDEM_PROD_MEDIDA_FK_COD_PE,     TBL_ORDEM_PROD_MEDIDA.ALTURA_ORIGINAL AS TBL_ORDEM_PROD_MEDIDA_ALTURA_OR,     TBL_ORDEM_PROD_MEDIDA.LARGURA_ORIGINAL AS TBL_ORDEM_PROD_MEDIDA_LARGURA_O,     TBL_ORDEM_PROD_MEDIDA.QUANTIDADE AS TBL_ORDEM_PROD_MEDIDA_QUANTIDAD,     TBL_ORDEM_PROD_MEDIDA.ALTURA AS TBL_ORDEM_PROD_MEDIDA_ALTURA,     TBL_ORDEM_PROD_MEDIDA.LARGURA AS TBL_ORDEM_PROD_MEDIDA_LARGURA,     TBL_PECA_PROJETO.DESCRICAO_ABREVIADA AS TBL_PECA_PROJETO_DESCRICAO_ABRE,     TBL_PECA_PROJETO.DESCRICAO AS TBL_PECA_PROJETO_DESCRICAO  FROM      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_ORCAMENTO TBL_ORCAMENTO ON TBL_CLIENTE.PK_CODIGO = TBL_ORCAMENTO.FK_CLIENTE      INNER JOIN TBL_PROJETO TBL_PROJETO ON TBL_ORCAMENTO.FK_PROJETO = TBL_PROJETO.PK_CODIGO      INNER JOIN TBL_LISTA_DE_PROD_DO_ORCA TBL_LISTA_DE_PROD_DO_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_ORCAMENTO      INNER JOIN TBL_VALOR_TOTAL_ORCA TBL_VALOR_TOTAL_ORCA ON TBL_ORCAMENTO.PK_CODIGO = TBL_VALOR_TOTAL_ORCA.FK_CODIGO_ORCAMENTO      INNER JOIN TBL_FORMA_PAGAMENTO TBL_FORMA_PAGAMENTO ON TBL_ORCAMENTO.FK_FORMA_PAGAMENTO = TBL_FORMA_PAGAMENTO.PK_CODIGO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ORCAMENTO.FK_COR = TBL_COR_FERRAG_PROJETO.COD_COR      INNER JOIN TBL_ORDEM_PRODUCAO TBL_ORDEM_PRODUCAO ON TBL_ORCAMENTO.PK_CODIGO = TBL_ORDEM_PRODUCAO.FK_COD_ORCAMENTO      INNER JOIN TBL_ORDEM_PROD_MEDIDA TBL_ORDEM_PROD_MEDIDA ON TBL_ORDEM_PRODUCAO.FK_COD_ORCAMENTO = TBL_ORDEM_PROD_MEDIDA.FK_ORDEM_PRODUCAO      INNER JOIN TBL_PECA_PROJETO TBL_PECA_PROJETO ON TBL_ORDEM_PROD_MEDIDA.FK_COD_PECA = TBL_PECA_PROJETO.PK_CODIGO      INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_LISTA_DE_PROD_DO_ORCA.FK_COD_PRODUTO = TBL_PRODUTO.PK_CODIGO      INNER JOIN TBL_IMAGEM_PROJETO TBL_IMAGEM_PROJETO ON TBL_PROJETO.PK_CODIGO = TBL_IMAGEM_PROJETO.FK_CODIGO_PROJETO,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA WHERE TBL_PRODUTO.FK_COD_TIPO_PRODUTO < 6 and TBL_ORCAMENTO.PK_CODIGO = '" + pCodOrcamento + "'");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioOrdemProducao.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioPrecoProduto(String pOrdenacao, String pTipoProduto, String pNomeRelatorio) {
        try {
            this.conectar();
            this.executarSQL("select TBL_PRODUTO.PK_CODIGO      , TBL_PRODUTO.FK_COD_TIPO_PRODUTO     , TBL_PRODUTO.STATUS     , TBL_PRODUTO.PESO_LIQUIDO     , TBL_PRODUTO.PESO_BRUTO     , TBL_PRODUTO.FK_COD_FOR     , TBL_PRODUTO.OBSERVACAO     , TBL_PRODUTO.UNIDADE_MEDIDA     , TBL_PRODUTO.NOME     , TBL_PRODUTO.FK_COD_COR     , TBL_PRODUTO.FK_COD_ESPESSURA     , TBL_PRODUTO.TEMPERADO_COMUM     , TBL_PRODUTO.FK_COD_IMAGEM     , TBL_PRECO_IMPO_PROD.PK_CODIGO     , TBL_PRECO_IMPO_PROD.ICMS     , TBL_PRECO_IMPO_PROD.IPI     , TBL_PRECO_IMPO_PROD.SUB_TRIBUTARIA     , TBL_PRECO_IMPO_PROD.FRETE     , TBL_PRECO_IMPO_PROD.LUCRO     , TBL_PRECO_IMPO_PROD.PRECO_CUSTO     , TBL_PRECO_IMPO_PROD.PRECO_FINAL     , TBL_PRECO_IMPO_PROD.PRE_TOTAL_CUSTO     , TBL_PRECO_IMPO_PROD.VALOR_DESPESAS from TBL_PRODUTO inner join TBL_PRECO_IMPO_PROD ON TBL_PRODUTO.PK_CODIGO = TBL_PRECO_IMPO_PROD.PK_CODIGO " + pTipoProduto + " " + pOrdenacao + ";");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/" + pNomeRelatorio + "");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioContaPagar(int pCodigoConta) {
        try {
            this.conectar();
            this.executarSQL("SELECT     TBL_LISTA_DE_PARC_CONTA_PAG.NUMERO_PARCELA AS TBL_LISTA_DE_PARC_CONTA_PAG_NUM,     TBL_LISTA_DE_PARC_CONTA_PAG.DATA_VENCIMENTO AS TBL_LISTA_DE_PARC_CONTA_PAG_DAT,     TBL_LISTA_DE_PARC_CONTA_PAG.STATUS AS TBL_LISTA_DE_PARC_CONTA_PAG_STA,     TBL_LISTA_DE_PARC_CONTA_PAG.VALOR_PARCIAL AS TBL_LISTA_DE_PARC_CONTA_PAG_VAL,     TBL_LISTA_DE_PARC_CONTA_PAG.JUROS_POR_ATRASO AS TBL_LISTA_DE_PARC_CONTA_PAG_JUR,     TBL_LISTA_DE_PARC_CONTA_PAG.VALOR_PAGAR AS TBL_LISTA_DE_PARC_CONTA_PAG_VAL,     TBL_LISTA_DE_PARC_CONTA_PAG.DATA_PAGAMENTO AS TBL_LISTA_DE_PARC_CONTA_PAG_DAT,     TBL_LISTA_DE_PARC_CONTA_PAG.NUMERO_DOCUMENTO AS TBL_LISTA_DE_PARC_CONTA_PAG_NUM,     TBL_CONTAS_PAGAR.PK_CODIGO AS TBL_CONTAS_PAGAR_PK_CODIGO,     TBL_CONTAS_PAGAR.STATUS AS TBL_CONTAS_PAGAR_STATUS,     TBL_CONTAS_PAGAR.FK_COD_FORNECEDOR AS TBL_CONTAS_PAGAR_FK_COD_FORNECE,     TBL_CONTAS_PAGAR.FK_COD_FORMA_PAGAMENTO AS TBL_CONTAS_PAGAR_FK_COD_FORMA_P,     TBL_CONTAS_PAGAR.FK_COD_TIPO_PAGAMENTO AS TBL_CONTAS_PAGAR_FK_COD_TIPO_PA,     TBL_CONTAS_PAGAR.DESCONTO AS TBL_CONTAS_PAGAR_DESCONTO,     TBL_CONTAS_PAGAR.VALOR_PAGAR AS TBL_CONTAS_PAGAR_VALOR_PAGAR,     TBL_CONTAS_PAGAR.VALOR_BRUTO AS TBL_CONTAS_PAGAR_VALOR_BRUTO,     TBL_CONTAS_PAGAR.JUROS AS TBL_CONTAS_PAGAR_JUROS,     TBL_CONTAS_PAGAR.VALOR_ENTRADA AS TBL_CONTAS_PAGAR_VALOR_ENTRADA,     TBL_FORNECEDOR.PK_CODIGO AS TBL_FORNECEDOR_PK_CODIGO,     TBL_FORNECEDOR.NOME AS TBL_FORNECEDOR_NOME,     TBL_FORNECEDOR.LOGRADOURO AS TBL_FORNECEDOR_LOGRADOURO,     TBL_FORNECEDOR.BAIRRO AS TBL_FORNECEDOR_BAIRRO,     TBL_FORNECEDOR.CIDADE AS TBL_FORNECEDOR_CIDADE,     TBL_FORNECEDOR.UF AS TBL_FORNECEDOR_UF,     TBL_FORNECEDOR.CEP AS TBL_FORNECEDOR_CEP,     TBL_FORNECEDOR.CGC AS TBL_FORNECEDOR_CGC,     TBL_FORNECEDOR.INSCRICAO_ESTADUAL AS TBL_FORNECEDOR_INSCRICAO_ESTADU,     TBL_FORNECEDOR.TELEFONE AS TBL_FORNECEDOR_TELEFONE,     TBL_FORNECEDOR.FAX AS TBL_FORNECEDOR_FAX,     TBL_FORNECEDOR.EMAIL AS TBL_FORNECEDOR_EMAIL,     TBL_FORNECEDOR.RESPONSAVEL_FORNECEDOR AS TBL_FORNECEDOR_RESPONSAVEL_FORN,     TBL_FORNECEDOR.CELULAR AS TBL_FORNECEDOR_CELULAR,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_CONTAS_PAGAR.OBSERVACAO AS TBL_CONTAS_PAGAR_OBSERVACAO,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_EMPRESA_LOGOMARCA.CAMINHO_IMAGEM AS TBL_EMPRESA_LOGOMARCA_CAMINHO_I,     TBL_EMPRESA.PK_CODIGO AS TBL_EMPRESA_PK_CODIGO  FROM      TBL_FORNECEDOR INNER JOIN TBL_CONTAS_PAGAR ON TBL_FORNECEDOR.PK_CODIGO = TBL_CONTAS_PAGAR.FK_COD_FORNECEDOR     INNER JOIN TBL_LISTA_DE_PARC_CONTA_PAG ON TBL_CONTAS_PAGAR.PK_CODIGO = TBL_LISTA_DE_PARC_CONTA_PAG.FK_COD_CONTA,     TBL_EMPRESA_LOGOMARCA INNER JOIN TBL_EMPRESA ON TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA = TBL_EMPRESA.PK_CODIGO WHERE TBL_CONTAS_PAGAR.PK_CODIGO = " + pCodigoConta + ";");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioContaPagar.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioContaReceber(int pCodigoConta) {
        try {
            this.conectar();
            this.executarSQL("SELECT     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_EMPRESA_LOGOMARCA.CAMINHO_IMAGEM AS TBL_EMPRESA_LOGOMARCA_CAMINHO_I,     TBL_EMPRESA.PK_CODIGO AS TBL_EMPRESA_PK_CODIGO,     TBL_CLIENTE.PK_CODIGO AS TBL_CLIENTE_PK_CODIGO,     TBL_CLIENTE.NOME AS TBL_CLIENTE_NOME,     TBL_CLIENTE.ENDERECO AS TBL_CLIENTE_ENDERECO,     TBL_CLIENTE.BAIRRO AS TBL_CLIENTE_BAIRRO,     TBL_CLIENTE.CIDADE AS TBL_CLIENTE_CIDADE,     TBL_CLIENTE.UF AS TBL_CLIENTE_UF,     TBL_CLIENTE.CEP AS TBL_CLIENTE_CEP,     TBL_CLIENTE.CGC AS TBL_CLIENTE_CGC,     TBL_CLIENTE.INSCRICAO_ESTADUAL AS TBL_CLIENTE_INSCRICAO_ESTADUAL,     TBL_CLIENTE.TELEFONE AS TBL_CLIENTE_TELEFONE,     TBL_CLIENTE.FAX AS TBL_CLIENTE_FAX,     TBL_CLIENTE.EMAIL AS TBL_CLIENTE_EMAIL,     TBL_CLIENTE.CELULAR AS TBL_CLIENTE_CELULAR,     TBL_CLIENTE.ANOTACOES AS TBL_CLIENTE_ANOTACOES,     TBL_CONTAS_RECEBER.STATUS AS TBL_CONTAS_RECEBER_STATUS,     TBL_CONTAS_RECEBER.FK_COD_CLIENTE AS TBL_CONTAS_RECEBER_FK_COD_CLIEN,     TBL_CONTAS_RECEBER.FK_COD_FORMA_PAGAMENTO AS TBL_CONTAS_RECEBER_FK_COD_FORMA,     TBL_CONTAS_RECEBER.FK_COD_TIPO_PAGAMENTO AS TBL_CONTAS_RECEBER_FK_COD_TIPO_,     TBL_CONTAS_RECEBER.OBSERVACAO AS TBL_CONTAS_RECEBER_OBSERVACAO,     TBL_CONTAS_RECEBER.DESCONTO AS TBL_CONTAS_RECEBER_DESCONTO,     TBL_CONTAS_RECEBER.FK_CRIACAO AS TBL_CONTAS_RECEBER_FK_CRIACAO,     TBL_CONTAS_RECEBER.FK_ALTERACAO AS TBL_CONTAS_RECEBER_FK_ALTERACAO,     TBL_CONTAS_RECEBER.VALOR_BRUTO AS TBL_CONTAS_RECEBER_VALOR_BRUTO,     TBL_CONTAS_RECEBER.VALOR_RECEBER AS TBL_CONTAS_RECEBER_VALOR_RECEBE,     TBL_CONTAS_RECEBER.JUROS AS TBL_CONTAS_RECEBER_JUROS,     TBL_CONTAS_RECEBER.VALOR_ENTRADA AS TBL_CONTAS_RECEBER_VALOR_ENTRAD,     TBL_CONTAS_RECEBER.FK_CAIXA_CONTA AS TBL_CONTAS_RECEBER_FK_CAIXA_CON,     TBL_LISTA_DE_PARC_CONTA_REC.NUMERO_PARCELA AS TBL_LISTA_DE_PARC_CONTA_REC_NUM,     TBL_LISTA_DE_PARC_CONTA_REC.DATA_VENCIMENTO AS TBL_LISTA_DE_PARC_CONTA_REC_DAT,     TBL_LISTA_DE_PARC_CONTA_REC.STATUS AS TBL_LISTA_DE_PARC_CONTA_REC_STA,     TBL_LISTA_DE_PARC_CONTA_REC.VALOR_RECEBER AS TBL_LISTA_DE_PARC_CONTA_REC_VAL,     TBL_LISTA_DE_PARC_CONTA_REC.DATA_RECEBIMENTO AS TBL_LISTA_DE_PARC_CONTA_REC_DAT,     TBL_LISTA_DE_PARC_CONTA_REC.NUMERO_DOCUMENTO AS TBL_LISTA_DE_PARC_CONTA_REC_NUM,     TBL_CONTAS_RECEBER.PK_CODIGO AS TBL_CONTAS_RECEBER_PK_CODIGO  FROM      TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA INNER JOIN TBL_EMPRESA TBL_EMPRESA ON TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA = TBL_EMPRESA.PK_CODIGO,      TBL_CLIENTE TBL_CLIENTE INNER JOIN TBL_CONTAS_RECEBER TBL_CONTAS_RECEBER ON TBL_CLIENTE.PK_CODIGO = TBL_CONTAS_RECEBER.FK_COD_CLIENTE      INNER JOIN TBL_LISTA_DE_PARC_CONTA_REC TBL_LISTA_DE_PARC_CONTA_REC ON TBL_CONTAS_RECEBER.PK_CODIGO = TBL_LISTA_DE_PARC_CONTA_REC.FK_COD_CONTA WHERE TBL_CONTAS_RECEBER.PK_CODIGO = " + pCodigoConta + ";");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioContaReceber.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioForcecedor() {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_FORNECEDOR.PK_CODIGO AS TBL_FORNECEDOR_PK_CODIGO,     TBL_FORNECEDOR.NOME AS TBL_FORNECEDOR_NOME,     TBL_FORNECEDOR.LOGRADOURO AS TBL_FORNECEDOR_LOGRADOURO,     TBL_FORNECEDOR.BAIRRO AS TBL_FORNECEDOR_BAIRRO,     TBL_FORNECEDOR.CIDADE AS TBL_FORNECEDOR_CIDADE,     TBL_FORNECEDOR.UF AS TBL_FORNECEDOR_UF,     TBL_FORNECEDOR.CEP AS TBL_FORNECEDOR_CEP,     TBL_FORNECEDOR.CGC AS TBL_FORNECEDOR_CGC,     TBL_FORNECEDOR.INSCRICAO_ESTADUAL AS TBL_FORNECEDOR_INSCRICAO_ESTADU,     TBL_FORNECEDOR.TELEFONE AS TBL_FORNECEDOR_TELEFONE,     TBL_FORNECEDOR.FAX AS TBL_FORNECEDOR_FAX,     TBL_FORNECEDOR.EMAIL AS TBL_FORNECEDOR_EMAIL,     TBL_FORNECEDOR.RESPONSAVEL_FORNECEDOR AS TBL_FORNECEDOR_RESPONSAVEL_FORN,     TBL_FORNECEDOR.DIAS_VENCIMENTO AS TBL_FORNECEDOR_DIAS_VENCIMENTO,     TBL_FORNECEDOR.PRAZO_ENTREGA AS TBL_FORNECEDOR_PRAZO_ENTREGA,     TBL_FORNECEDOR.FISICO_JURIDICO AS TBL_FORNECEDOR_FISICO_JURIDICO,     TBL_FORNECEDOR.CELULAR AS TBL_FORNECEDOR_CELULAR,     TBL_FORNECEDOR.ANOTACOES AS TBL_FORNECEDOR_ANOTACOES,     TBL_FORNECEDOR.DATA_CADASTRO AS TBL_FORNECEDOR_DATA_CADASTRO,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM  FROM      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA,     TBL_FORNECEDOR TBL_FORNECEDOR;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioFornecedor.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioProdutos() {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.FK_COD_TIPO_PRODUTO AS TBL_PRODUTO_FK_COD_TIPO_PRODUTO,     TBL_PRODUTO.STATUS AS TBL_PRODUTO_STATUS,     TBL_PRODUTO.PESO_LIQUIDO AS TBL_PRODUTO_PESO_LIQUIDO,     TBL_PRODUTO.PESO_BRUTO AS TBL_PRODUTO_PESO_BRUTO,     TBL_PRODUTO.FK_COD_FOR AS TBL_PRODUTO_FK_COD_FOR,     TBL_PRODUTO.OBSERVACAO AS TBL_PRODUTO_OBSERVACAO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_PRODUTO.FK_COD_COR AS TBL_PRODUTO_FK_COD_COR,     TBL_PRODUTO.FK_COD_ESPESSURA AS TBL_PRODUTO_FK_COD_ESPESSURA,     TBL_PRODUTO.TEMPERADO_COMUM AS TBL_PRODUTO_TEMPERADO_COMUM,     TBL_PRODUTO.FK_COD_IMAGEM AS TBL_PRODUTO_FK_COD_IMAGEM,     TBL_TIPO_DE_PRODUTO.PK_CODIGO AS TBL_TIPO_DE_PRODUTO_PK_CODIGO,     TBL_TIPO_DE_PRODUTO.NOME AS TBL_TIPO_DE_PRODUTO_NOME,     TBL_TIPO_DE_PRODUTO.POSSUI_MEDIDAS AS TBL_TIPO_DE_PRODUTO_POSSUI_MEDI  FROM      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA,      TBL_PRODUTO TBL_PRODUTO INNER JOIN TBL_TIPO_DE_PRODUTO TBL_TIPO_DE_PRODUTO ON TBL_PRODUTO.FK_COD_TIPO_PRODUTO = TBL_TIPO_DE_PRODUTO.PK_CODIGO;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioProduto.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }

    public boolean relatorioEstoqueProdutos() {
        try {
            this.conectar();
            this.executarSQL("SELECT      TBL_PRODUTO.PK_CODIGO AS TBL_PRODUTO_PK_CODIGO,     TBL_PRODUTO.NOME AS TBL_PRODUTO_NOME,     TBL_PRODUTO.STATUS AS TBL_PRODUTO_STATUS,     TBL_PRODUTO.PESO_LIQUIDO AS TBL_PRODUTO_PESO_LIQUIDO,     TBL_PRODUTO.PESO_BRUTO AS TBL_PRODUTO_PESO_BRUTO,     TBL_PRODUTO.UNIDADE_MEDIDA AS TBL_PRODUTO_UNIDADE_MEDIDA,     TBL_ESTOQUE.PK_CODIGO AS TBL_ESTOQUE_PK_CODIGO,     TBL_ESTOQUE.ESTOQUE_MINIMO AS TBL_ESTOQUE_ESTOQUE_MINIMO,     TBL_ESTOQUE.ESTOQUE_MAXIMO AS TBL_ESTOQUE_ESTOQUE_MAXIMO,     TBL_ESTOQUE.ESTOQUE_ATUAL AS TBL_ESTOQUE_ESTOQUE_ATUAL,     TBL_TIPO_DE_PRODUTO.NOME AS TBL_TIPO_DE_PRODUTO_NOME,     TBL_TIPO_DE_PRODUTO.PK_CODIGO AS TBL_TIPO_DE_PRODUTO_PK_CODIGO,     TBL_COR_FERRAG_PROJETO.COD_COR AS TBL_COR_FERRAG_PROJETO_COD_COR,     TBL_COR_FERRAG_PROJETO.COR AS TBL_COR_FERRAG_PROJETO_COR,     TBL_EMPRESA.NOME_FANTASIA AS TBL_EMPRESA_NOME_FANTASIA,     TBL_EMPRESA.LOGRADOURO AS TBL_EMPRESA_LOGRADOURO,     TBL_EMPRESA.BAIRRO AS TBL_EMPRESA_BAIRRO,     TBL_EMPRESA.CIDADE AS TBL_EMPRESA_CIDADE,     TBL_EMPRESA.UF AS TBL_EMPRESA_UF,     TBL_EMPRESA.CEP AS TBL_EMPRESA_CEP,     TBL_EMPRESA.TELEFONE AS TBL_EMPRESA_TELEFONE,     TBL_EMPRESA.FAX AS TBL_EMPRESA_FAX,     TBL_EMPRESA.CELULAR AS TBL_EMPRESA_CELULAR,     TBL_EMPRESA.EMAIL AS TBL_EMPRESA_EMAIL,     TBL_EMPRESA.INSCRICAO_ESTADUAL AS TBL_EMPRESA_INSCRICAO_ESTADUAL,     TBL_EMPRESA.CNPJ AS TBL_EMPRESA_CNPJ,     TBL_EMPRESA.SITE AS TBL_EMPRESA_SITE,     TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA AS TBL_EMPRESA_LOGOMARCA_FK_CODIGO,     TBL_EMPRESA_LOGOMARCA.IMAGEM AS TBL_EMPRESA_LOGOMARCA_IMAGEM,     TBL_EMPRESA_LOGOMARCA.CAMINHO_IMAGEM AS TBL_EMPRESA_LOGOMARCA_CAMINHO_I,     TBL_EMPRESA.PK_CODIGO AS TBL_EMPRESA_PK_CODIGO,     TBL_EMPRESA.RAZAO_SOCIAL AS TBL_EMPRESA_RAZAO_SOCIAL  FROM      TBL_TIPO_DE_PRODUTO TBL_TIPO_DE_PRODUTO INNER JOIN TBL_PRODUTO TBL_PRODUTO ON TBL_TIPO_DE_PRODUTO.PK_CODIGO = TBL_PRODUTO.FK_COD_TIPO_PRODUTO      INNER JOIN TBL_ESTOQUE TBL_ESTOQUE ON TBL_PRODUTO.PK_CODIGO = TBL_ESTOQUE.FK_PRODUTO      INNER JOIN TBL_COR_FERRAG_PROJETO TBL_COR_FERRAG_PROJETO ON TBL_ESTOQUE.FK_COR_FERRAGEM = TBL_COR_FERRAG_PROJETO.COD_COR,      TBL_EMPRESA TBL_EMPRESA INNER JOIN TBL_EMPRESA_LOGOMARCA TBL_EMPRESA_LOGOMARCA ON TBL_EMPRESA.PK_CODIGO = TBL_EMPRESA_LOGOMARCA.FK_CODIGO_EMPRESA ORDER BY TBL_PRODUTO.PK_CODIGO;");
            JRResultSetDataSource jrRS = new JRResultSetDataSource(this.getResultSet());
            InputStream caminhoRelatorio = this.getClass().getClassLoader().getResourceAsStream("ArquivosJasper/relatorioEstoqueProdutos.jasper");
            JasperPrint jasperPrint = JasperFillManager.fillReport((InputStream)caminhoRelatorio, new HashMap(), (JRDataSource)jrRS);
            JasperExportManager.exportReportToPdfFile((JasperPrint)jasperPrint, (String)this.NOME_DO_RELATORIO);
            File file = new File(this.NOME_DO_RELATORIO);
            try {
                Desktop.getDesktop().open(file);
            }
            catch (Exception e) {
                JOptionPane.showConfirmDialog(null, e);
            }
            file.deleteOnExit();
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro:", 0);
            return false;
        }
        return true;
    }
}

